# Sample .travis.yml for R projects

language: r
#warnings_are_errors: true
sudo: required

r_packages:
  - covr
  - RUnit
 
# works just as well as via "r_packages:"
#before_script:   
#  - Rscript -e 'install.packages("covr", repos="http://cran.rstudio.com")'

after_success:
  - Rscript -e 'library(covr);codecov()'  
